[package]
name = "rustapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.3"
actix-web = "4.5.1"
async-trait = "0.1.77"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.7.3", features = ["mysql", "runtime-tokio"] }
dotenv = "0.15.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.77"
